{"additions": 2, "auther_ref": "import_exceptions", "auther_sha": "6c10fd765590a7abba92e6b3755f31c0cc88b82a", "author": "guitargeek", "body": "#### PR description:\r\n\r\nToday I wanted to use the `edmDumpEventContent` script with python3, which can be easily done by automatically updating the code with `python-modernize` except for one hiccup: the `import exceptions` line in *PhysicsTools/PythonAnalysis/python/cmstools.py*. Following the information in this post [1], the exceptions can be just taken from the builtins instead of the exceptions module in python 2 as well, which makes the code python 3 compatible. There was also another spot in CMSSW where the former `exceptions` module was imported, so I changed this one too.\r\n\r\n[1] https://stackoverflow.com/questions/27030933/python-2s-exceptions-module-is-missing-in-python3-where-did-its-contents-go\r\n\r\n#### PR validation:\r\n\r\nI can use `edmDumpEventContent` with python 3 when I take this PR and run `python-modernize -n -w .` on top of it.\r\n\r\n#### if this PR is a backport please specify the original PR:\r\n\r\nNo backport intended.\r\n", "branch": "master", "changed_files": 2, "comments": 8, "commits": 1, "created_at": "1572306755", "deletions": 4, "labels": ["analysis-pending", "code-checks-approved", "comparison-available", "orp-pending", "pending-signatures", "reconstruction-pending", "tests-approved"], "milestone": "CMSSW_11_0_X", "number": 28299, "release-notes": [], "review_comments": 0, "state": "open", "title": "Take python exceptions from builtins", "updated_at": "1572350159", "user": "guitargeek"}