{"additions": 14, "auther_ref": "pylint-242-encoding", "auther_sha": "534a3dc92b3b6babc1c1e298cbd89217f506881f", "author": "cms-sw", "body": "pylint 2.4.2 failed to build for python3 due to encding issues [a]. We patch it to avoid ignore special characters in RWADME.rst file.\r\n\r\n[a]\r\n```\r\n      File \"/build/cmsbld/jenkins/workspace/build-any-ib/w/tmp/pip-2z0c36hw-build/setup.py\", line 60, in <module>\r\n        long_description = stream.read()\r\n      File \"/build/cmsbld/jenkins/workspace/build-any-ib/w/slc7_amd64_gcc820/external/python3/3.6.4-pafccj/lib/python3.6/encodings/ascii.py\", line 26, in decode\r\n        return codecs.ascii_decode(input, self.errors)[0]\r\n    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 4020: ordinal not in range(128)\r\n```", "branch": "IB/CMSSW_11_0_X/master", "changed_files": 3, "comments": 1, "commits": 1, "created_at": "1570512231", "deletions": 2, "labels": ["comparison-pending", "externals-pending", "orp-pending", "pending-signatures", "tests-pending"], "number": 5267, "release-notes": [], "review_comments": 0, "state": "open", "title": "[PYLint] fixed encoding issue with pylint 2.4.2", "updated_at": "1570512256", "user": "smuzaffar"}